-- Change only Due slots; preserve hourly New slots, recipient checks and deep links.
do $$
declare definition text; old_block text; new_block text;
begin
 definition:=pg_get_functiondef('leadlaju_private.enqueue_sales_contact_reminders(timestamptz)'::regprocedure);
 old_block:=$old$ if extract(minute from local_time)>=15 then return 0; end if;
 slot_at:=date_trunc('hour',local_time) at time zone 'Asia/Kuala_Lumpur';
 foreach kind in array array['sales_new_daily','sales_due_daily'] loop
 if (kind='sales_new_daily' and extract(hour from local_time) not in (10,11,12,13,14,15,16)) or
 (kind='sales_due_daily' and extract(hour from local_time) not in (9,15,21)) then continue; end if;$old$;
 new_block:=$new$ foreach kind in array array['sales_new_daily','sales_due_daily'] loop
 if kind='sales_new_daily' then
   if extract(hour from local_time) not in (10,11,12,13,14,15,16) or extract(minute from local_time)>=15 then continue; end if;
   slot_at:=date_trunc('hour',local_time) at time zone 'Asia/Kuala_Lumpur';
 else
   if extract(hour from local_time) not in (9,11,13,15,17) or extract(minute from local_time)<30 or extract(minute from local_time)>=45 then continue; end if;
   slot_at:=(date_trunc('hour',local_time)+interval '30 minutes') at time zone 'Asia/Kuala_Lumpur';
 end if;$new$;
 if position(old_block in definition)=0 then raise exception 'Unexpected daily reminder schedule definition'; end if;
 execute replace(definition,old_block,new_block);
end $$;

-- Retire unsent Due reminders generated by the previous schedule.
update public.notification_outbox set sent_at=now(),claimed_at=null,last_error='Cancelled: Follow Up Due schedule replaced'
where sent_at is null and notification_type='sales_due_daily';
